language: java
jdk:
- oraclejdk8
sudo: required

branches:
only: master

script:
- bash build.sh
- ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
