@echo off
set OS_AUTH_URL=http://10.28.3.240:5000/v3
set OS_IDENTITY_API_VERSION=3
set OS_TENANT_NAME=c312ad9239f44b70979712a8c4232b63
set OS_PROJECT_NAME=fj_danielcaballero_at06-desktop
set OS_SERVER_NAME=must.be.changed
set OS_USERNAME=danielcaballero
set OS_PASSWORD=
set OS_DOMAIN_NAME=fundacion-jala
set OS_FLAVOR=f1.desktop.small
set OS_IMAGE=ubuntu-16.04-amd64-server_18062018
set OS_KEY_PAIR_NAME=danielcaballero
set OS_REGION_NAME=bootstack-jalasoft
set OS_KEY_PAIR_PATH=C:\\Users\\Administrator\\Downloads\\danielcaballero.pem
set OS_TENANT_NAME2=
set OS_PROJECT_NAME2=fj_danielcaballero_at06-lab
set OS_FLAVOR2=f1.desktop.small
set OS_SERVER_NAME2=linux-deployment