Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = ENV['OS_KEY_PAIR_PATH']
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name = ENV['OS_DOMAIN_NAME']
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']
    os.keypair_name = ENV['OS_KEY_PAIR_NAME']
    os.region = ENV['OS_REGION_NAME']
    os.image = ENV['OS_IMAGE']
  end

  config.vm.define 'linux-server-1' do |s|
    s.vm.provision "docker"
    s.vm.provision "docker_compose", compose_version: '1.21.2'	
    s.vm.provider :openstack do |os, override|
      os.tenant_name = ENV['OS_TENANT_NAME']
      os.project_name = ENV['OS_PROJECT_NAME']
      os.server_name = ENV['OS_SERVER_NAME']
      os.flavor = ENV['OS_FLAVOR']
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end

  config.vm.define 'linux-server-2' do |s|
    s.vm.provision "shell", path: "install.sh"	
    s.vm.provider :openstack do |os, override|
      os.tenant_name = ENV['OS_TENANT_NAME2']
      os.project_name = ENV['OS_PROJECT_NAME2']
      os.server_name = ENV['OS_SERVER_NAME2']
      os.flavor = ENV['OS_FLAVOR2']
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end
end
